import Link from "next/link";
import { createKamal } from "@/lib/admin-actions";

export default async function NewKamalPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const { error } = await searchParams;
  return <div className="mx-auto max-w-3xl"><Link href="/admin/kamals" className="text-sm font-semibold text-slate-500 hover:text-emerald-800">← Tous les Kamals</Link><header className="mt-5"><p className="text-sm font-semibold text-emerald-700">Nouveau cycle</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Créer un Kamal</h1><p className="mt-2 text-sm leading-6 text-slate-500">Préparez une lecture collective et répartissez les 30 Juz entre les membres actifs.</p></header>
    {error && <p role="alert" className="mt-5 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm text-amber-900">{error === "no-members" ? "Ajoutez au moins un membre actif avant de créer un Kamal." : "Vérifiez les informations saisies."}</p>}
    <form action={createKamal} className="mt-6 overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm"><div className="space-y-7 p-5 sm:p-8"><section><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-emerald-100 text-sm font-bold text-emerald-800">1</span><div><h2 className="font-bold text-slate-900">Informations du Kamal</h2><p className="text-xs text-slate-500">Donnez un titre facile à reconnaître.</p></div></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-600 sm:col-span-2">Nom du cycle<input name="titre" required minLength={3} maxLength={120} placeholder="Ex. Kamal du vendredi" className={inputClass} /></label><label className="text-xs font-semibold text-slate-600">Date limite <span className="font-normal text-slate-400">(facultative)</span><input name="dateLimite" type="datetime-local" className={inputClass} /></label></div></section>
    <div className="h-px bg-slate-100"/><section><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-emerald-100 text-sm font-bold text-emerald-800">2</span><div><h2 className="font-bold text-slate-900">Répartition des Juz</h2><p className="text-xs text-slate-500">Vous pourrez modifier chaque affectation ensuite.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="flex cursor-pointer gap-3 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4 transition has-[:checked]:ring-2 has-[:checked]:ring-emerald-600"><input type="radio" name="mode" value="alphabetique" defaultChecked className="mt-0.5 accent-emerald-700"/><span><span className="block text-sm font-semibold text-slate-900">Ordre alphabétique</span><span className="mt-1 block text-xs leading-5 text-slate-500">Répartition régulière selon le nom des membres.</span></span></label><label className="flex cursor-pointer gap-3 rounded-2xl border border-slate-200 p-4 transition has-[:checked]:border-emerald-200 has-[:checked]:bg-emerald-50/60 has-[:checked]:ring-2 has-[:checked]:ring-emerald-600"><input type="radio" name="mode" value="aleatoire" className="mt-0.5 accent-emerald-700"/><span><span className="block text-sm font-semibold text-slate-900">Mélanger les affectations</span><span className="mt-1 block text-xs leading-5 text-slate-500">Attribue les Juz aux membres dans un ordre aléatoire.</span></span></label></div><div className="mt-4 flex gap-3 rounded-xl bg-slate-50 p-3.5 text-xs leading-5 text-slate-500"><span className="text-emerald-700">ⓘ</span><p>Les 30 Juz seront répartis entre les membres actifs. Si le groupe compte moins de 30 personnes, certains recevront plusieurs Juz.</p></div></section></div><div className="flex flex-col-reverse gap-3 border-t border-slate-100 bg-slate-50/70 p-5 sm:flex-row sm:justify-end sm:px-8"><Link href="/admin/kamals" className="inline-flex min-h-11 items-center justify-center rounded-xl px-5 text-sm font-semibold text-slate-600 hover:bg-white">Annuler</Link><button className="min-h-11 rounded-xl bg-emerald-800 px-6 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-900">Créer et publier</button></div></form>
  </div>;
}
const inputClass = "mt-1.5 min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-slate-900 placeholder:text-slate-400 focus:border-emerald-500 focus:outline-none focus:ring-4 focus:ring-emerald-500/10";
