import Link from "next/link";
import { prisma } from "@/lib/prisma";

export default async function DashboardPage() {
  const kamals = await prisma.kamal.findMany({ where: { archivedAt: null }, orderBy: { createdAt: "desc" }, take: 6, include: { assignments: { where: { statut: { in: ["EN_ATTENTE", "CONFIRME"] } }, include: { user: true } } } });
  const active = kamals.find((k) => k.statut === "EN_COURS");
  const current = active ?? kamals[0];
  const confirmed = current?.assignments.filter((a) => a.statut === "CONFIRME").length ?? 0;
  const total = current?.assignments.length ?? 0;
  const waiting = current?.assignments.filter((a) => a.statut === "EN_ATTENTE").length ?? 0;
  const percent = total ? Math.round((confirmed / total) * 100) : 0;
  const membersCount = await prisma.user.count({ where: { role: "MEMBER", actif: true } });
  const today = new Intl.DateTimeFormat("fr-FR", { weekday: "long", day: "numeric", month: "long" }).format(new Date());

  return <div className="space-y-8">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold capitalize text-emerald-700">{today}</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Vue d’ensemble</h1><p className="mt-2 text-sm text-slate-500">La progression de vos lectures, en un seul endroit.</p></div><Link href="/admin/kamals/new" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-800 px-5 text-sm font-semibold text-white shadow-sm transition hover:bg-emerald-900"><span className="text-lg leading-none">+</span> Créer un Kamal</Link></header>

    <section className="grid gap-4 sm:grid-cols-3">
      <Stat icon="◉" label="Juz confirmés" value={`${confirmed}`} detail={`sur ${total || 30} Juz`} tone="green" />
      <Stat icon="◷" label="En attente" value={`${waiting}`} detail="à confirmer" tone="amber" />
      <Stat icon="♧" label="Membres actifs" value={`${membersCount}`} detail="dans votre groupe" tone="slate" />
    </section>

    {current ? <section className="overflow-hidden rounded-3xl border border-emerald-950/10 bg-white shadow-sm">
      <div className="relative overflow-hidden bg-emerald-950 px-5 py-6 text-white sm:px-8 sm:py-8"><div className="pointer-events-none absolute -right-12 -top-24 h-64 w-64 rounded-full border border-white/10"/><div className="pointer-events-none absolute -right-2 -top-14 h-44 w-44 rounded-full border border-white/10"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-emerald-200"><span className="h-2 w-2 rounded-full bg-emerald-300" />{active ? "Kamal en cours" : "Dernier Kamal"}</div><h2 className="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">{current.titre}</h2><p className="mt-2 text-sm text-emerald-100/75">{current.dateLimite ? `Échéance · ${current.dateLimite.toLocaleDateString("fr-FR", { day: "numeric", month: "long" })}` : "Aucune date limite définie"}</p></div><Link href={`/admin/kamals/${current.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 self-start rounded-xl border border-white/20 px-4 text-sm font-semibold text-white transition hover:bg-white/10 sm:self-auto">Ouvrir le suivi <span aria-hidden="true">↗</span></Link></div>
        <div className="relative mt-7"><div className="flex items-end justify-between"><div><span className="text-4xl font-bold tracking-tight">{confirmed}</span><span className="ml-1 text-lg text-emerald-100/70">/ 30</span></div><span className="text-sm font-semibold text-emerald-100">{percent}% terminé</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-emerald-300 transition-all" style={{ width: `${percent}%` }} /></div></div>
      </div>
      <div className="p-5 sm:p-8"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-slate-900">État des lectures</h3><span className="text-xs text-slate-400">30 Juz</span></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 30 }, (_, index) => index + 1).map((juz) => { const assignment = current.assignments.find((a) => a.juzNumber === juz); const done = assignment?.statut === "CONFIRME"; return <div key={juz} className="flex min-w-0 items-center gap-3 rounded-xl border border-slate-100 bg-slate-50/70 px-3 py-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-lg text-xs font-bold ${done ? "bg-emerald-100 text-emerald-800" : "bg-white text-slate-500 ring-1 ring-slate-200"}`}>{juz}</span><span className="min-w-0 flex-1 truncate text-sm font-medium text-slate-700">{assignment ? `${assignment.user.prenom} ${assignment.user.nom}` : "Non attribué"}</span><span className={`shrink-0 text-[11px] font-semibold ${done ? "text-emerald-700" : "text-amber-700"}`}>{done ? "Confirmé" : "En attente"}</span></div>; })}</div></div>
    </section> : <section className="rounded-3xl border border-dashed border-emerald-300 bg-white px-6 py-12 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-emerald-50 text-2xl text-emerald-800">☾</span><h2 className="mt-4 text-lg font-bold text-slate-900">Votre premier Kamal vous attend</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Créez un cycle de lecture, répartissez les Juz entre les membres et suivez les confirmations ici.</p><Link href={membersCount ? "/admin/kamals/new" : "/admin/members"} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-xl bg-emerald-800 px-5 text-sm font-semibold text-white">{membersCount ? "Créer un Kamal" : "Ajouter des membres"}</Link></section>}

    <section><div className="mb-4 flex items-end justify-between gap-4"><div><h2 className="text-xl font-bold tracking-tight text-slate-950">Vos Kamals</h2><p className="mt-1 text-sm text-slate-500">Retrouvez les cycles récents.</p></div><Link href="/admin/kamals" className="text-sm font-semibold text-emerald-800 hover:text-emerald-950">Tout voir <span aria-hidden="true">→</span></Link></div><div className="grid gap-3 md:grid-cols-2">{kamals.slice(0, 4).map((kamal) => { const done = kamal.assignments.filter(a => a.statut === "CONFIRME").length; return <Link key={kamal.id} href={`/admin/kamals/${kamal.id}`} className="group flex items-center justify-between gap-4 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-md"><div className="flex min-w-0 items-center gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-lg text-emerald-800">▤</span><div className="min-w-0"><p className="truncate font-semibold text-slate-900">{kamal.titre}</p><p className="mt-1 text-xs text-slate-500">{statusLabel(kamal.statut)} · {done}/30 confirmés</p></div></div><span className="text-slate-300 transition group-hover:translate-x-0.5 group-hover:text-emerald-700">→</span></Link>; })}{kamals.length === 0 && <p className="rounded-2xl border border-slate-200 bg-white p-5 text-sm text-slate-500">Aucun cycle créé pour le moment.</p>}</div></section>
  </div>;
}

function Stat({ icon, label, value, detail, tone }: { icon: string; label: string; value: string; detail: string; tone: "green" | "amber" | "slate" }) { const color = tone === "green" ? "bg-emerald-50 text-emerald-800" : tone === "amber" ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-600"; return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{label}</p><span className={`grid h-9 w-9 place-items-center rounded-xl text-lg ${color}`}>{icon}</span></div><div className="mt-4 flex items-baseline gap-2"><span className="text-3xl font-bold tracking-tight text-slate-950">{value}</span><span className="text-xs text-slate-400">{detail}</span></div></div>; }
function statusLabel(status: string) { return ({ BROUILLON: "Brouillon", EN_COURS: "En cours", TERMINE: "Terminé", EXPIRE: "Expiré" } as Record<string, string>)[status] ?? status; }
