import { redirect } from "next/navigation";
import Image from "next/image";
import { getSession } from "@/lib/auth";
import { LoginForm } from "@/components/login-form";

export default async function LoginPage() {
  if (await getSession()) redirect("/admin/dashboard");
  return <main className="grid min-h-screen bg-white lg:grid-cols-[1.05fr_.95fr]"><section className="relative hidden overflow-hidden bg-emerald-950 px-12 py-12 text-white lg:flex lg:flex-col lg:justify-between xl:px-20"><div className="absolute -right-40 -top-40 h-[34rem] w-[34rem] rounded-full border border-white/10"/><div className="absolute -right-20 -top-20 h-[26rem] w-[26rem] rounded-full border border-white/10"/><div className="relative flex items-center gap-3"><Image src="/kaamil-dahira-logo.jpeg" alt="Logo Kaamil Dahira FWK" width={48} height={48} className="h-12 w-12 shrink-0 rounded-xl object-contain" /><span><span className="block text-sm font-black tracking-wide">kaamil</span><span className="block text-xs tracking-[.2em] text-emerald-200">Dahira FWK</span></span></div><div className="relative max-w-xl"><div className="mb-5 h-1 w-12 rounded-full bg-emerald-300"/><p className="text-sm font-semibold uppercase tracking-[.17em] text-emerald-200">Ensemble, jusqu’au dernier Jukki</p><h1 className="mt-4 text-5xl font-bold leading-[1.12] tracking-tight xl:text-6xl">Une lecture partagée, un suivi tout simple.</h1><p className="mt-6 max-w-lg text-base leading-7 text-emerald-100/75">Organisez les Kamals de votre communauté et suivez chaque confirmation depuis un seul espace.</p><div className="mt-10 flex items-center gap-2 text-sm text-emerald-100"><span className="grid h-7 w-7 place-items-center rounded-full bg-emerald-400/15 text-emerald-200">✓</span>Simple à organiser <span className="mx-2 text-emerald-700">·</span> Accessible partout</div></div><p className="relative text-xs text-emerald-100/45">Kamal Manager · Espace responsable</p></section><section className="grid min-h-screen place-items-center px-5 py-10 sm:px-8"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><Image src="/kaamil-dahira-logo.jpeg" alt="Logo Kaamil Dahira FWK" width={44} height={44} className="h-11 w-11 shrink-0 rounded-xl object-contain" /><span><span className="block text-sm font-black tracking-wide text-slate-900">kaamil</span><span className="block text-xs tracking-[.18em] text-emerald-700">Dahira FWK</span></span></div><div className="mb-8"><p className="text-sm font-semibold text-emerald-700">Bienvenue</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Connexion responsable</h2><p className="mt-2 text-sm leading-6 text-slate-500">Connectez-vous pour gérer les membres et les cycles de lecture.</p></div><LoginForm /></div></section></main>;
}
